Vagrant.configure("2") do |config|

  config.vm.define "jenkins" do |jenkins|
    jenkins.vm.box = "ubuntu/jammy64"
    jenkins.vm.hostname = "jenkins"

    jenkins.vm.network "private_network", ip: "192.168.56.10"

    jenkins.vm.network "forwarded_port",
      guest: 8080,
      host: 8080,
      auto_correct: true

    jenkins.vm.provider "virtualbox" do |vb|
      vb.memory = 1024
      vb.cpus = 1
    end

    jenkins.vm.provision "shell", path: "scripts/setup-node.sh"
    jenkins.vm.provision "shell", path: "scripts/setup-jenkins.sh"
  end

  config.vm.define "prod" do |prod|
    prod.vm.box = "ubuntu/jammy64"
    prod.vm.hostname = "prod"

    prod.vm.network "private_network", ip: "192.168.56.20"

    prod.vm.provider "virtualbox" do |vb|
      vb.memory = 1024
      vb.cpus = 1
    end

    prod.vm.provision "shell", path: "scripts/setup-node.sh"
    prod.vm.provision "shell", path: "scripts/setup-prod.sh"
  end

end